// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: proto/audio.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AudioStreamService_StreamAudio_FullMethodName = "/ai.speech.ingress.AudioStreamService/StreamAudio"
)

// AudioStreamServiceClient is the client API for AudioStreamService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AudioStreamServiceClient interface {
	StreamAudio(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[AudioFrame, StreamAck], error)
}

type audioStreamServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAudioStreamServiceClient(cc grpc.ClientConnInterface) AudioStreamServiceClient {
	return &audioStreamServiceClient{cc}
}

func (c *audioStreamServiceClient) StreamAudio(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[AudioFrame, StreamAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AudioStreamService_ServiceDesc.Streams[0], AudioStreamService_StreamAudio_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AudioFrame, StreamAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AudioStreamService_StreamAudioClient = grpc.ClientStreamingClient[AudioFrame, StreamAck]

// AudioStreamServiceServer is the server API for AudioStreamService service.
// All implementations must embed UnimplementedAudioStreamServiceServer
// for forward compatibility.
type AudioStreamServiceServer interface {
	StreamAudio(grpc.ClientStreamingServer[AudioFrame, StreamAck]) error
	mustEmbedUnimplementedAudioStreamServiceServer()
}

// UnimplementedAudioStreamServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAudioStreamServiceServer struct{}

func (UnimplementedAudioStreamServiceServer) StreamAudio(grpc.ClientStreamingServer[AudioFrame, StreamAck]) error {
	return status.Error(codes.Unimplemented, "method StreamAudio not implemented")
}
func (UnimplementedAudioStreamServiceServer) mustEmbedUnimplementedAudioStreamServiceServer() {}
func (UnimplementedAudioStreamServiceServer) testEmbeddedByValue()                            {}

// UnsafeAudioStreamServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AudioStreamServiceServer will
// result in compilation errors.
type UnsafeAudioStreamServiceServer interface {
	mustEmbedUnimplementedAudioStreamServiceServer()
}

func RegisterAudioStreamServiceServer(s grpc.ServiceRegistrar, srv AudioStreamServiceServer) {
	// If the following call panics, it indicates UnimplementedAudioStreamServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AudioStreamService_ServiceDesc, srv)
}

func _AudioStreamService_StreamAudio_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AudioStreamServiceServer).StreamAudio(&grpc.GenericServerStream[AudioFrame, StreamAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AudioStreamService_StreamAudioServer = grpc.ClientStreamingServer[AudioFrame, StreamAck]

// AudioStreamService_ServiceDesc is the grpc.ServiceDesc for AudioStreamService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AudioStreamService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ai.speech.ingress.AudioStreamService",
	HandlerType: (*AudioStreamServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamAudio",
			Handler:       _AudioStreamService_StreamAudio_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/audio.proto",
}
