// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/audio.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AudioFrame struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	InteractionId  string                 `protobuf:"bytes,1,opt,name=interactionId,proto3" json:"interactionId,omitempty"`
	TenantId       string                 `protobuf:"bytes,2,opt,name=tenantId,proto3" json:"tenantId,omitempty"`
	Audio          []byte                 `protobuf:"bytes,3,opt,name=audio,proto3" json:"audio,omitempty"`
	AudioOffsetMs  int64                  `protobuf:"varint,4,opt,name=audioOffsetMs,proto3" json:"audioOffsetMs,omitempty"`
	EndOfUtterance bool                   `protobuf:"varint,5,opt,name=endOfUtterance,proto3" json:"endOfUtterance,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AudioFrame) Reset() {
	*x = AudioFrame{}
	mi := &file_proto_audio_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioFrame) ProtoMessage() {}

func (x *AudioFrame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_audio_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioFrame.ProtoReflect.Descriptor instead.
func (*AudioFrame) Descriptor() ([]byte, []int) {
	return file_proto_audio_proto_rawDescGZIP(), []int{0}
}

func (x *AudioFrame) GetInteractionId() string {
	if x != nil {
		return x.InteractionId
	}
	return ""
}

func (x *AudioFrame) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *AudioFrame) GetAudio() []byte {
	if x != nil {
		return x.Audio
	}
	return nil
}

func (x *AudioFrame) GetAudioOffsetMs() int64 {
	if x != nil {
		return x.AudioOffsetMs
	}
	return 0
}

func (x *AudioFrame) GetEndOfUtterance() bool {
	if x != nil {
		return x.EndOfUtterance
	}
	return false
}

type StreamAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InteractionId string                 `protobuf:"bytes,1,opt,name=interactionId,proto3" json:"interactionId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamAck) Reset() {
	*x = StreamAck{}
	mi := &file_proto_audio_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamAck) ProtoMessage() {}

func (x *StreamAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_audio_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamAck.ProtoReflect.Descriptor instead.
func (*StreamAck) Descriptor() ([]byte, []int) {
	return file_proto_audio_proto_rawDescGZIP(), []int{1}
}

func (x *StreamAck) GetInteractionId() string {
	if x != nil {
		return x.InteractionId
	}
	return ""
}

var File_proto_audio_proto protoreflect.FileDescriptor

const file_proto_audio_proto_rawDesc = "" +
	"\n" +
	"\x11proto/audio.proto\x12\x11ai.speech.ingress\"\xb2\x01\n" +
	"\n" +
	"AudioFrame\x12$\n" +
	"\rinteractionId\x18\x01 \x01(\tR\rinteractionId\x12\x1a\n" +
	"\btenantId\x18\x02 \x01(\tR\btenantId\x12\x14\n" +
	"\x05audio\x18\x03 \x01(\fR\x05audio\x12$\n" +
	"\raudioOffsetMs\x18\x04 \x01(\x03R\raudioOffsetMs\x12&\n" +
	"\x0eendOfUtterance\x18\x05 \x01(\bR\x0eendOfUtterance\"1\n" +
	"\tStreamAck\x12$\n" +
	"\rinteractionId\x18\x01 \x01(\tR\rinteractionId2b\n" +
	"\x12AudioStreamService\x12L\n" +
	"\vStreamAudio\x12\x1d.ai.speech.ingress.AudioFrame\x1a\x1c.ai.speech.ingress.StreamAck(\x01B'Z%ai-speech-ingress-service/proto;protob\x06proto3"

var (
	file_proto_audio_proto_rawDescOnce sync.Once
	file_proto_audio_proto_rawDescData []byte
)

func file_proto_audio_proto_rawDescGZIP() []byte {
	file_proto_audio_proto_rawDescOnce.Do(func() {
		file_proto_audio_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_audio_proto_rawDesc), len(file_proto_audio_proto_rawDesc)))
	})
	return file_proto_audio_proto_rawDescData
}

var file_proto_audio_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_audio_proto_goTypes = []any{
	(*AudioFrame)(nil), // 0: ai.speech.ingress.AudioFrame
	(*StreamAck)(nil),  // 1: ai.speech.ingress.StreamAck
}
var file_proto_audio_proto_depIdxs = []int32{
	0, // 0: ai.speech.ingress.AudioStreamService.StreamAudio:input_type -> ai.speech.ingress.AudioFrame
	1, // 1: ai.speech.ingress.AudioStreamService.StreamAudio:output_type -> ai.speech.ingress.StreamAck
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_audio_proto_init() }
func file_proto_audio_proto_init() {
	if File_proto_audio_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_audio_proto_rawDesc), len(file_proto_audio_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_audio_proto_goTypes,
		DependencyIndexes: file_proto_audio_proto_depIdxs,
		MessageInfos:      file_proto_audio_proto_msgTypes,
	}.Build()
	File_proto_audio_proto = out.File
	file_proto_audio_proto_goTypes = nil
	file_proto_audio_proto_depIdxs = nil
}
